include:
  - ./docker-compose.indyscan.yml
  - ./docker-compose.elastic.yml

networks:
  proxy:
    name: proxy
    external: true
  indyscan:
    name: indyscan
    driver: bridge
  esnet:
    name: esnet
    driver: bridge

volumes:
  indyscan-es:
    driver: local
